### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by adhoc-transbot** [ingadhoc/purchase#27]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] purchase_global_discount
- [ ] purchase_prices_update
- [ ] purchase_quotation_products
- [ ] purchase_suggest
- [ ] purchase_suggest_extended
- [ ] purchase_usability
- [ ] purchase_usability_return_invoicing
