### ISSUE TITLE
Migration to version 13.0

### ISSUE THREAD

**Issue by jjscarafia** [ingadhoc/purchase#86]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

# Modules to migrate

- [ ] purchase_stock_ux
- [ ] purchase_mrp_ux
- [ ] purchase_global_discount
- [ ] purchase_suggest
- [ ] purchase_ux
- [ ] purchase_stock_analytic
- [ ] purchase_quotation_products
